// <auto-generated />
using System;
using Api_SASL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_SASL.Migrations
{
    [DbContext(typeof(DevSaslContext))]
    [Migration("20260422035306_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_SASL.Models.AsignacionEmpleado", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("DiasLaborales")
                        .HasColumnType("int")
                        .HasColumnName("dias_laborales");

                    b.Property<int>("IdHorario")
                        .HasColumnType("int")
                        .HasColumnName("id_horario");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdUsuario", "IdServicio");

                    b.HasIndex("DiasLaborales");

                    b.HasIndex("IdHorario");

                    b.HasIndex("IdServicio");

                    b.ToTable("Asignacion_empleados", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionMaquinarium", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<int>("IdMaquinaria")
                        .HasColumnType("int")
                        .HasColumnName("id_maquinaria");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdServicio", "IdMaquinaria");

                    b.HasIndex("IdMaquinaria");

                    b.ToTable("Asignacion_maquinaria", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionRecurso", b =>
                {
                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<int>("IdRecurso")
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.HasKey("IdServicio", "IdRecurso");

                    b.HasIndex("IdRecurso");

                    b.ToTable("Asignacion_recursos", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionUniforme", b =>
                {
                    b.Property<int>("IdAsignacionUniforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_asignacion_uniforme");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacionUniforme"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.Property<DateOnly?>("FechaDevolucion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_devolucion");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("IdUniforme")
                        .HasColumnType("int")
                        .HasColumnName("id_uniforme");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdAsignacionUniforme");

                    b.HasIndex("IdUniforme");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Asignacion_uniformes", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Capacitacione", b =>
                {
                    b.Property<int>("IdCapacitacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_capacitacion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCapacitacion"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdCapacitacion");

                    b.ToTable("Capacitaciones");
                });

            modelBuilder.Entity("Api_SASL.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ContactoEmergencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("contacto_emergencia");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_cliente");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Direccion", b =>
                {
                    b.Property<int>("IdDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDireccion"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("calle");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdZona")
                        .HasColumnType("int")
                        .HasColumnName("id_zona");

                    b.Property<int>("NCasa")
                        .HasColumnType("int")
                        .HasColumnName("n_casa");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdDireccion");

                    b.HasIndex("IdZona");

                    b.ToTable("Direccion", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.DocumentosUsuario", b =>
                {
                    b.Property<int>("IdDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_documento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocumento"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("archivo");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateOnly>("FechaSubida")
                        .HasColumnType("date")
                        .HasColumnName("fecha_subida");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("TipoDeDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tipo_de_documento");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdDocumento");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Documentos_usuarios", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Dominio", b =>
                {
                    b.Property<int>("IdDominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_dominio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDominio"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Dominio1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dominio");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdDominio");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("Api_SASL.Models.EstadoCalidad", b =>
                {
                    b.Property<int>("IdEstadoCalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado_calidad");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstadoCalidad"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("EstadoCalidad1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("estado_calidad");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdEstadoCalidad");

                    b.ToTable("Estado_calidad", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.HistorialEstadoMaquina", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHistorial"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_cambio");

                    b.Property<int>("IdEstadoCalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_calidad");

                    b.Property<int>("IdMaquinaria")
                        .HasColumnType("int")
                        .HasColumnName("id_maquinaria");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdEstadoCalidad");

                    b.HasIndex("IdMaquinaria");

                    b.ToTable("Historial_estado_maquina", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Horario", b =>
                {
                    b.Property<int>("IdHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_horario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdHorario"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<TimeOnly>("HoraEntrada")
                        .HasColumnType("time")
                        .HasColumnName("hora_entrada");

                    b.Property<TimeOnly>("HoraSalida")
                        .HasColumnType("time")
                        .HasColumnName("hora_salida");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdHorario");

                    b.ToTable("Horario", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Incidente", b =>
                {
                    b.Property<int>("IdIncidente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_incidente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdIncidente"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdIncidente");

                    b.HasIndex("IdServicio");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("Api_SASL.Models.Mantenimiento", b =>
                {
                    b.Property<int>("IdMantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mantenimiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMantenimiento"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("FechaMantenimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_mantenimiento");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdMantenimiento");

                    b.ToTable("Mantenimiento", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.MantenimientosMaquinarium", b =>
                {
                    b.Property<int>("IdMaquinaria")
                        .HasColumnType("int")
                        .HasColumnName("id_maquinaria");

                    b.Property<int>("IdMantenimiento")
                        .HasColumnType("int")
                        .HasColumnName("id_mantenimiento");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdMaquinaria", "IdMantenimiento");

                    b.HasIndex("IdMantenimiento");

                    b.ToTable("Mantenimientos_maquinaria", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Maquinarium", b =>
                {
                    b.Property<int>("IdMaquinaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_maquinaria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaquinaria"));

                    b.Property<string>("CodigoInv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("codigo_inv");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEstadoCalidad")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_calidad");

                    b.Property<int>("IdMarcaMaquinaria")
                        .HasColumnType("int")
                        .HasColumnName("id_marca_maquinaria");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdTipoMaquinaria")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo_maquinaria");

                    b.Property<string>("NombreMaquinaria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_maquinaria");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdMaquinaria");

                    b.HasIndex("IdEstadoCalidad");

                    b.HasIndex("IdMarcaMaquinaria");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipoMaquinaria");

                    b.ToTable("Maquinaria");
                });

            modelBuilder.Entity("Api_SASL.Models.MarcaMaquinarium", b =>
                {
                    b.Property<int>("IdMarcaMaquinaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca_maquinaria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarcaMaquinaria"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_marca");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdMarcaMaquinaria");

                    b.HasIndex("IdPais");

                    b.ToTable("Marca_maquinaria", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Memorial", b =>
                {
                    b.Property<int>("IdMemorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_memorial");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMemorial"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int")
                        .HasColumnName("id_empleado");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdMemorial");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("Memorial", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Provedore", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int")
                        .HasColumnName("id_producto");

                    b.Property<int>("Nit")
                        .HasColumnType("int")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdProducto");

                    b.ToTable("Provedores");
                });

            modelBuilder.Entity("Api_SASL.Models.Recurso", b =>
                {
                    b.Property<int>("IdRecurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRecurso"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdRecurso");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipo");

                    b.ToTable("Recursos");
                });

            modelBuilder.Entity("Api_SASL.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre_rol");

                    b.Property<int>("Salario")
                        .HasColumnType("int")
                        .HasColumnName("salario");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Api_SASL.Models.Servicio", b =>
                {
                    b.Property<int>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicio"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("costo");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("FechaFinal")
                        .HasColumnType("date")
                        .HasColumnName("fecha_final");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    b.Property<int>("TipoServicio")
                        .HasColumnType("int")
                        .HasColumnName("tipo_servicio");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdServicio");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("TipoServicio");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.ServicioTerminado", b =>
                {
                    b.Property<int>("IdServicioTerminado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_servicio_terminado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicioTerminado"));

                    b.Property<string>("Comentarios")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("comentarios");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<int>("Satisfaccion")
                        .HasColumnType("int")
                        .HasColumnName("satisfaccion");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdServicioTerminado");

                    b.HasIndex("IdServicio");

                    b.HasIndex("Satisfaccion");

                    b.ToTable("Servicio_terminado", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.SubDominio", b =>
                {
                    b.Property<int>("IdSubDominio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sub_dominio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubDominio"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("detalle");

                    b.Property<int>("IdDominio")
                        .HasColumnType("int")
                        .HasColumnName("id_dominio");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdSubDominio");

                    b.HasIndex("IdDominio");

                    b.ToTable("Sub_dominios", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoCliente", b =>
                {
                    b.Property<int>("IdTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_telefono");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefono"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdDetalle")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    b.Property<int>("Telefono")
                        .HasColumnType("int")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdTelefono");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDetalle");

                    b.ToTable("Telefono_cliente", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoProveedor", b =>
                {
                    b.Property<int>("IdTelefono")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_telefono");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefono"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdDetalle")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<int>("Telefono")
                        .HasColumnType("int")
                        .HasColumnName("telefono");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdTelefono");

                    b.HasIndex("IdDetalle");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Telefono_proveedor", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoUsuario", b =>
                {
                    b.Property<int>("IdTelefonoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_telefono_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTelefonoUsuario"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("IdDetalle")
                        .HasColumnType("int")
                        .HasColumnName("id_detalle");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("TelefonoUsuario1")
                        .HasColumnType("int")
                        .HasColumnName("telefono_usuario");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdTelefonoUsuario");

                    b.HasIndex("IdDetalle");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Telefono_usuarios", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.Uniforme", b =>
                {
                    b.Property<int>("IdUniforme")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_uniforme");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUniforme"));

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreUniforme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_uniforme");

                    b.Property<int>("Talla")
                        .HasColumnType("int")
                        .HasColumnName("talla");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdUniforme");

                    b.ToTable("Uniformes");
                });

            modelBuilder.Entity("Api_SASL.Models.UsuarioTrabajador", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int>("Ci")
                        .HasColumnType("int")
                        .HasColumnName("ci");

                    b.Property<string>("Codigo2fa")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("codigo2fa");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("Expiracion")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiracion");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<int>("IdDireccion")
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    b.Property<int>("IdEstadoCivil")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_civil");

                    b.Property<int>("IdGenero")
                        .HasColumnType("int")
                        .HasColumnName("id_genero");

                    b.Property<int>("IdGradoAcademico")
                        .HasColumnType("int")
                        .HasColumnName("id_grado_academico");

                    b.Property<int>("IdPais")
                        .HasColumnType("int")
                        .HasColumnName("id_pais");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_usuario");

                    b.Property<bool?>("SegundoFactorPendiente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("segundo_factor_pendiente");

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdDireccion");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdGenero");

                    b.HasIndex("IdGradoAcademico");

                    b.HasIndex("IdPais");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuario_trabajador", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.UsuariosCapacitacione", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdCapacitacion")
                        .HasColumnType("int")
                        .HasColumnName("id_capacitacion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("estado");

                    b.HasKey("IdUsuario", "IdCapacitacion");

                    b.HasIndex("IdCapacitacion");

                    b.ToTable("Usuarios_capacitaciones", (string)null);
                });

            modelBuilder.Entity("CarrerasUsuario", b =>
                {
                    b.Property<int>("IdCarrera")
                        .HasColumnType("int")
                        .HasColumnName("id_carrera");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("IdCarrera", "IdUsuario");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Carreras_usuario", (string)null);
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionEmpleado", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "DiasLaboralesNavigation")
                        .WithMany("AsignacionEmpleados")
                        .HasForeignKey("DiasLaborales")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_empleados_dias");

                    b.HasOne("Api_SASL.Models.Horario", "IdHorarioNavigation")
                        .WithMany("AsignacionEmpleados")
                        .HasForeignKey("IdHorario")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_empleados_horario");

                    b.HasOne("Api_SASL.Models.Servicio", "IdServicioNavigation")
                        .WithMany("AsignacionEmpleados")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_empleados_servicio");

                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdUsuarioNavigation")
                        .WithMany("AsignacionEmpleados")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_empleados_usuario");

                    b.Navigation("DiasLaboralesNavigation");

                    b.Navigation("IdHorarioNavigation");

                    b.Navigation("IdServicioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionMaquinarium", b =>
                {
                    b.HasOne("Api_SASL.Models.Maquinarium", "IdMaquinariaNavigation")
                        .WithMany("AsignacionMaquinaria")
                        .HasForeignKey("IdMaquinaria")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_maquinaria_maquinaria");

                    b.HasOne("Api_SASL.Models.Servicio", "IdServicioNavigation")
                        .WithMany("AsignacionMaquinaria")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_maquinaria_servicio");

                    b.Navigation("IdMaquinariaNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionRecurso", b =>
                {
                    b.HasOne("Api_SASL.Models.Recurso", "IdRecursoNavigation")
                        .WithMany("AsignacionRecursos")
                        .HasForeignKey("IdRecurso")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_recursos_recurso");

                    b.HasOne("Api_SASL.Models.Servicio", "IdServicioNavigation")
                        .WithMany("AsignacionRecursos")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_recursos_servicio");

                    b.Navigation("IdRecursoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.AsignacionUniforme", b =>
                {
                    b.HasOne("Api_SASL.Models.Uniforme", "IdUniformeNavigation")
                        .WithMany("AsignacionUniformes")
                        .HasForeignKey("IdUniforme")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_uniformes_uniforme");

                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdUsuarioNavigation")
                        .WithMany("AsignacionUniformes")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Asignacion_uniformes_usuario");

                    b.Navigation("IdUniformeNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Cliente", b =>
                {
                    b.HasOne("Api_SASL.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_direccion");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdEmpresaNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_Cliente_empresa");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("IdEmpresaNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Direccion", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "IdZonaNavigation")
                        .WithMany("Direccions")
                        .HasForeignKey("IdZona")
                        .IsRequired()
                        .HasConstraintName("FK_Direccion_id_zona");

                    b.Navigation("IdZonaNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.DocumentosUsuario", b =>
                {
                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdUsuarioNavigation")
                        .WithMany("DocumentosUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Documentos_usuarios_usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.HistorialEstadoMaquina", b =>
                {
                    b.HasOne("Api_SASL.Models.EstadoCalidad", "IdEstadoCalidadNavigation")
                        .WithMany("HistorialEstadoMaquinas")
                        .HasForeignKey("IdEstadoCalidad")
                        .IsRequired()
                        .HasConstraintName("FK_Historial_estado_maquina_estado");

                    b.HasOne("Api_SASL.Models.Maquinarium", "IdMaquinariaNavigation")
                        .WithMany("HistorialEstadoMaquinas")
                        .HasForeignKey("IdMaquinaria")
                        .IsRequired()
                        .HasConstraintName("FK_Historial_estado_maquina_maquinaria");

                    b.Navigation("IdEstadoCalidadNavigation");

                    b.Navigation("IdMaquinariaNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Incidente", b =>
                {
                    b.HasOne("Api_SASL.Models.Servicio", "IdServicioNavigation")
                        .WithMany("Incidentes")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Incidentes_servicio");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.MantenimientosMaquinarium", b =>
                {
                    b.HasOne("Api_SASL.Models.Mantenimiento", "IdMantenimientoNavigation")
                        .WithMany("MantenimientosMaquinaria")
                        .HasForeignKey("IdMantenimiento")
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimientos_maquinaria_mantenimiento");

                    b.HasOne("Api_SASL.Models.Maquinarium", "IdMaquinariaNavigation")
                        .WithMany("MantenimientosMaquinaria")
                        .HasForeignKey("IdMaquinaria")
                        .IsRequired()
                        .HasConstraintName("FK_Mantenimientos_maquinaria_maquinaria");

                    b.Navigation("IdMantenimientoNavigation");

                    b.Navigation("IdMaquinariaNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Maquinarium", b =>
                {
                    b.HasOne("Api_SASL.Models.EstadoCalidad", "IdEstadoCalidadNavigation")
                        .WithMany("Maquinaria")
                        .HasForeignKey("IdEstadoCalidad")
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_estado_calidad");

                    b.HasOne("Api_SASL.Models.MarcaMaquinarium", "IdMarcaMaquinariaNavigation")
                        .WithMany("Maquinaria")
                        .HasForeignKey("IdMarcaMaquinaria")
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_marca");

                    b.HasOne("Api_SASL.Models.Provedore", "IdProveedorNavigation")
                        .WithMany("Maquinaria")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_proveedor");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdTipoMaquinariaNavigation")
                        .WithMany("Maquinaria")
                        .HasForeignKey("IdTipoMaquinaria")
                        .IsRequired()
                        .HasConstraintName("FK_Maquinaria_tipo");

                    b.Navigation("IdEstadoCalidadNavigation");

                    b.Navigation("IdMarcaMaquinariaNavigation");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdTipoMaquinariaNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.MarcaMaquinarium", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "IdPaisNavigation")
                        .WithMany("MarcaMaquinaria")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Marca_maquinaria_pais");

                    b.Navigation("IdPaisNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Memorial", b =>
                {
                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdEmpleadoNavigation")
                        .WithMany("Memorials")
                        .HasForeignKey("IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Memorial_empleado");

                    b.Navigation("IdEmpleadoNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Provedore", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "IdEmpresaNavigation")
                        .WithMany("ProvedoreIdEmpresaNavigations")
                        .HasForeignKey("IdEmpresa")
                        .IsRequired()
                        .HasConstraintName("FK_Provedores_empresa");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdProductoNavigation")
                        .WithMany("ProvedoreIdProductoNavigations")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Provedores_producto");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Recurso", b =>
                {
                    b.HasOne("Api_SASL.Models.Provedore", "IdProveedorNavigation")
                        .WithMany("Recursos")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Recursos_proveedor");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdTipoNavigation")
                        .WithMany("Recursos")
                        .HasForeignKey("IdTipo")
                        .IsRequired()
                        .HasConstraintName("FK_Recursos_tipo");

                    b.Navigation("IdProveedorNavigation");

                    b.Navigation("IdTipoNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.Servicio", b =>
                {
                    b.HasOne("Api_SASL.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_cliente");

                    b.HasOne("Api_SASL.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_direccion");

                    b.HasOne("Api_SASL.Models.SubDominio", "TipoServicioNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("TipoServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_tipo_servicio");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("TipoServicioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.ServicioTerminado", b =>
                {
                    b.HasOne("Api_SASL.Models.Servicio", "IdServicioNavigation")
                        .WithMany("ServicioTerminados")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_terminado_servicio");

                    b.HasOne("Api_SASL.Models.SubDominio", "SatisfaccionNavigation")
                        .WithMany("ServicioTerminados")
                        .HasForeignKey("Satisfaccion")
                        .IsRequired()
                        .HasConstraintName("FK_Servicio_terminado_satisfaccion");

                    b.Navigation("IdServicioNavigation");

                    b.Navigation("SatisfaccionNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.SubDominio", b =>
                {
                    b.HasOne("Api_SASL.Models.Dominio", "IdDominioNavigation")
                        .WithMany("SubDominios")
                        .HasForeignKey("IdDominio")
                        .IsRequired()
                        .HasConstraintName("FK_Sub_dominios_id_dominio");

                    b.Navigation("IdDominioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoCliente", b =>
                {
                    b.HasOne("Api_SASL.Models.Cliente", "IdClienteNavigation")
                        .WithMany("TelefonoClientes")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_cliente_cliente");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdDetalleNavigation")
                        .WithMany("TelefonoClientes")
                        .HasForeignKey("IdDetalle")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_cliente_detalle");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetalleNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoProveedor", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "IdDetalleNavigation")
                        .WithMany("TelefonoProveedors")
                        .HasForeignKey("IdDetalle")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_proveedor_detalle");

                    b.HasOne("Api_SASL.Models.Provedore", "IdProveedorNavigation")
                        .WithMany("TelefonoProveedors")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_proveedor_proveedor");

                    b.Navigation("IdDetalleNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.TelefonoUsuario", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", "IdDetalleNavigation")
                        .WithMany("TelefonoUsuarios")
                        .HasForeignKey("IdDetalle")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_usuarios_detalle");

                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdUsuarioNavigation")
                        .WithMany("TelefonoUsuarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Telefono_usuarios_usuario");

                    b.Navigation("IdDetalleNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.UsuarioTrabajador", b =>
                {
                    b.HasOne("Api_SASL.Models.Direccion", "IdDireccionNavigation")
                        .WithMany("UsuarioTrabajadors")
                        .HasForeignKey("IdDireccion")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_direccion");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdEstadoCivilNavigation")
                        .WithMany("UsuarioTrabajadorIdEstadoCivilNavigations")
                        .HasForeignKey("IdEstadoCivil")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_estado_civil");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdGeneroNavigation")
                        .WithMany("UsuarioTrabajadorIdGeneroNavigations")
                        .HasForeignKey("IdGenero")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_genero");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdGradoAcademicoNavigation")
                        .WithMany("UsuarioTrabajadorIdGradoAcademicoNavigations")
                        .HasForeignKey("IdGradoAcademico")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_grado_academico");

                    b.HasOne("Api_SASL.Models.SubDominio", "IdPaisNavigation")
                        .WithMany("UsuarioTrabajadorIdPaisNavigations")
                        .HasForeignKey("IdPais")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_pais");

                    b.HasOne("Api_SASL.Models.Role", "IdRolNavigation")
                        .WithMany("UsuarioTrabajadors")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_trabajador_rol");

                    b.Navigation("IdDireccionNavigation");

                    b.Navigation("IdEstadoCivilNavigation");

                    b.Navigation("IdGeneroNavigation");

                    b.Navigation("IdGradoAcademicoNavigation");

                    b.Navigation("IdPaisNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Api_SASL.Models.UsuariosCapacitacione", b =>
                {
                    b.HasOne("Api_SASL.Models.Capacitacione", "IdCapacitacionNavigation")
                        .WithMany("UsuariosCapacitaciones")
                        .HasForeignKey("IdCapacitacion")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_capacitaciones_capacitacion");

                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", "IdUsuarioNavigation")
                        .WithMany("UsuariosCapacitaciones")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_capacitaciones_usuario");

                    b.Navigation("IdCapacitacionNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("CarrerasUsuario", b =>
                {
                    b.HasOne("Api_SASL.Models.SubDominio", null)
                        .WithMany()
                        .HasForeignKey("IdCarrera")
                        .IsRequired()
                        .HasConstraintName("FK_Carreras_usuario_carrera");

                    b.HasOne("Api_SASL.Models.UsuarioTrabajador", null)
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Carreras_usuario_usuario");
                });

            modelBuilder.Entity("Api_SASL.Models.Capacitacione", b =>
                {
                    b.Navigation("UsuariosCapacitaciones");
                });

            modelBuilder.Entity("Api_SASL.Models.Cliente", b =>
                {
                    b.Navigation("Servicios");

                    b.Navigation("TelefonoClientes");
                });

            modelBuilder.Entity("Api_SASL.Models.Direccion", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Servicios");

                    b.Navigation("UsuarioTrabajadors");
                });

            modelBuilder.Entity("Api_SASL.Models.Dominio", b =>
                {
                    b.Navigation("SubDominios");
                });

            modelBuilder.Entity("Api_SASL.Models.EstadoCalidad", b =>
                {
                    b.Navigation("HistorialEstadoMaquinas");

                    b.Navigation("Maquinaria");
                });

            modelBuilder.Entity("Api_SASL.Models.Horario", b =>
                {
                    b.Navigation("AsignacionEmpleados");
                });

            modelBuilder.Entity("Api_SASL.Models.Mantenimiento", b =>
                {
                    b.Navigation("MantenimientosMaquinaria");
                });

            modelBuilder.Entity("Api_SASL.Models.Maquinarium", b =>
                {
                    b.Navigation("AsignacionMaquinaria");

                    b.Navigation("HistorialEstadoMaquinas");

                    b.Navigation("MantenimientosMaquinaria");
                });

            modelBuilder.Entity("Api_SASL.Models.MarcaMaquinarium", b =>
                {
                    b.Navigation("Maquinaria");
                });

            modelBuilder.Entity("Api_SASL.Models.Provedore", b =>
                {
                    b.Navigation("Maquinaria");

                    b.Navigation("Recursos");

                    b.Navigation("TelefonoProveedors");
                });

            modelBuilder.Entity("Api_SASL.Models.Recurso", b =>
                {
                    b.Navigation("AsignacionRecursos");
                });

            modelBuilder.Entity("Api_SASL.Models.Role", b =>
                {
                    b.Navigation("UsuarioTrabajadors");
                });

            modelBuilder.Entity("Api_SASL.Models.Servicio", b =>
                {
                    b.Navigation("AsignacionEmpleados");

                    b.Navigation("AsignacionMaquinaria");

                    b.Navigation("AsignacionRecursos");

                    b.Navigation("Incidentes");

                    b.Navigation("ServicioTerminados");
                });

            modelBuilder.Entity("Api_SASL.Models.SubDominio", b =>
                {
                    b.Navigation("AsignacionEmpleados");

                    b.Navigation("Clientes");

                    b.Navigation("Direccions");

                    b.Navigation("Maquinaria");

                    b.Navigation("MarcaMaquinaria");

                    b.Navigation("ProvedoreIdEmpresaNavigations");

                    b.Navigation("ProvedoreIdProductoNavigations");

                    b.Navigation("Recursos");

                    b.Navigation("ServicioTerminados");

                    b.Navigation("Servicios");

                    b.Navigation("TelefonoClientes");

                    b.Navigation("TelefonoProveedors");

                    b.Navigation("TelefonoUsuarios");

                    b.Navigation("UsuarioTrabajadorIdEstadoCivilNavigations");

                    b.Navigation("UsuarioTrabajadorIdGeneroNavigations");

                    b.Navigation("UsuarioTrabajadorIdGradoAcademicoNavigations");

                    b.Navigation("UsuarioTrabajadorIdPaisNavigations");
                });

            modelBuilder.Entity("Api_SASL.Models.Uniforme", b =>
                {
                    b.Navigation("AsignacionUniformes");
                });

            modelBuilder.Entity("Api_SASL.Models.UsuarioTrabajador", b =>
                {
                    b.Navigation("AsignacionEmpleados");

                    b.Navigation("AsignacionUniformes");

                    b.Navigation("DocumentosUsuarios");

                    b.Navigation("Memorials");

                    b.Navigation("TelefonoUsuarios");

                    b.Navigation("UsuariosCapacitaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
